#!/usr/bin/python3
import json;
import sys;
import string;
import random;
from commons import eprint, exec;

NAME_LEN = 8;

payload = json.load(sys.stdin);
source = payload["source"];
eprint("source=", source);

space_name = ''.join(random.SystemRandom().choice(string.ascii_lowercase) for _ in range(NAME_LEN));


print(json.dumps([space_name]));

