resource_types:
- name: cf-test-space
  type: docker-image
  source:
    repository: kdvolder/cf-test-space-resource
resources:
- name: git
  type: git
  source:
    uri: git@github.com:kdvolder/cf-test-space-resource
    branch: master
    private_key: {{rsa_id}}
- name: docker-image
  type: docker-image
  source:
    username: {{docker_hub_username}}
    email: {{docker_hub_email}}
    password: {{docker_hub_password}}
    repository: kdvolder/cf-test-space-resource
- name: test-space
  type: cf-test-space
  source: 
    api_url: {{cf_api_url}}
    user: {{cf_user}}
    password: {{cf_password}}
    org: {{cf_org}}
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: git
    trigger: true
  - put: docker-image
    params:
      build: git
    get_params: 
      skip_download: true
- name: integration-test
  plan:
  - get: git
  - get: docker-image
    trigger: true
    params:
      skip_download: true
  - get: test-space
  - task: test-space-exists
    file: git/concourse/tasks/test-space-exists.yml
  - put: test-space
  - task: test-space-destroyed
    file: git/concourse/tasks/test-space-destroyed.yml
  
